name: jangbogo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.1
  smooth_page_indicator: ^1.2.0+3
  google_mlkit_text_recognition: ^0.13.0

dev_dependencies:
  build_runner: ^2.4.12
  floor_generator: ^1.5.0
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/prices/

  fonts:
    - family: pretendard
      fonts:
        - asset: assets/fonts/pretendard_regular.otf
